-- Baseline reproduisant le schema actuellement genere par Hibernate (ddl-auto: update).
-- Sur une base existante, Flyway ne l'execute pas (baseline-on-migrate + baseline-version: 1).
-- Sur une base neuve, ce script cree le schema initial identique a l'existant.

CREATE TABLE app_users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(255) NOT NULL,
    password      VARCHAR(255) NOT NULL,
    nom           VARCHAR(255),
    prenom        VARCHAR(255),
    role          VARCHAR(255) NOT NULL,
    date_creation TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_app_users_username UNIQUE (username)
);

CREATE TABLE quartiers (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom              VARCHAR(255) NOT NULL,
    tarif_livraison  DOUBLE PRECISION NOT NULL,
    CONSTRAINT uq_quartiers_nom UNIQUE (nom)
);

CREATE TABLE produits (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom          VARCHAR(255) NOT NULL,
    prix         NUMERIC(12, 2) NOT NULL,
    description  TEXT,
    stock        INTEGER NOT NULL,
    actif        BOOLEAN NOT NULL
);

CREATE TABLE commandes (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_client            VARCHAR(255) NOT NULL,
    telephone_client      VARCHAR(255) NOT NULL,
    email_client          VARCHAR(255),
    quartier_id           BIGINT NOT NULL,
    adresse_precise       VARCHAR(255) NOT NULL,
    latitude              DOUBLE PRECISION,
    longitude             DOUBLE PRECISION,
    date_heure_souhaitee  TIMESTAMP(6),
    statut                VARCHAR(255) NOT NULL,
    date_creation         TIMESTAMP(6) NOT NULL,
    livreur_id            BIGINT,
    CONSTRAINT fk_commandes_quartier FOREIGN KEY (quartier_id) REFERENCES quartiers (id),
    CONSTRAINT fk_commandes_livreur FOREIGN KEY (livreur_id) REFERENCES app_users (id)
);

CREATE TABLE commande_produits (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commande_id    BIGINT NOT NULL,
    produit_id     BIGINT NOT NULL,
    quantite       INTEGER NOT NULL,
    prix_unitaire  NUMERIC(12, 2) NOT NULL,
    CONSTRAINT fk_commande_produits_commande FOREIGN KEY (commande_id) REFERENCES commandes (id),
    CONSTRAINT fk_commande_produits_produit FOREIGN KEY (produit_id) REFERENCES produits (id)
);
