DO $$
BEGIN
    -- Drop orphan relation uq_app_users_username if it exists without being attached to an active app_users constraint
    IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'uq_app_users_username') 
       AND NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'app_users') THEN
        BEGIN
            EXECUTE 'DROP INDEX IF EXISTS uq_app_users_username CASCADE';
        EXCEPTION WHEN OTHERS THEN
            NULL;
        END;
    END IF;

    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'app_users') 
       AND NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'utilisateurs') THEN
        CREATE TABLE app_users (
            id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username      VARCHAR(255) NOT NULL,
            password      VARCHAR(255) NOT NULL,
            nom           VARCHAR(255),
            prenom        VARCHAR(255),
            role          VARCHAR(255) NOT NULL,
            date_creation TIMESTAMP(6) NOT NULL
        );
    END IF;

    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'app_users') THEN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_app_users_username') 
           AND NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'uq_app_users_username') THEN
            BEGIN
                ALTER TABLE app_users ADD CONSTRAINT uq_app_users_username UNIQUE (username);
            EXCEPTION WHEN OTHERS THEN
                NULL;
            END;
        END IF;
    END IF;

    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'quartiers') THEN
        CREATE TABLE quartiers (
            id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nom              VARCHAR(255) NOT NULL,
            tarif_livraison  DOUBLE PRECISION NOT NULL
        );
    END IF;

    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'quartiers') THEN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_quartiers_nom') 
           AND NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'uq_quartiers_nom') THEN
            BEGIN
                ALTER TABLE quartiers ADD CONSTRAINT uq_quartiers_nom UNIQUE (nom);
            EXCEPTION WHEN OTHERS THEN
                NULL;
            END;
        END IF;
    END IF;

    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'produits') THEN
        CREATE TABLE produits (
            id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nom          VARCHAR(255) NOT NULL,
            prix         NUMERIC(12, 2) NOT NULL,
            description  TEXT,
            stock        INTEGER NOT NULL,
            actif        BOOLEAN NOT NULL
        );
    END IF;

    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'commandes') THEN
        CREATE TABLE commandes (
            id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nom_client            VARCHAR(255) NOT NULL,
            telephone_client      VARCHAR(255) NOT NULL,
            email_client          VARCHAR(255),
            quartier_id           BIGINT NOT NULL,
            adresse_precise       VARCHAR(255) NOT NULL,
            latitude              DOUBLE PRECISION,
            longitude             DOUBLE PRECISION,
            date_heure_souhaitee  TIMESTAMP(6),
            statut                VARCHAR(255) NOT NULL,
            date_creation         TIMESTAMP(6) NOT NULL,
            livreur_id            BIGINT
        );
    END IF;

    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'commandes') THEN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_commandes_quartier') THEN
            BEGIN
                ALTER TABLE commandes ADD CONSTRAINT fk_commandes_quartier FOREIGN KEY (quartier_id) REFERENCES quartiers (id);
            EXCEPTION WHEN OTHERS THEN
                NULL;
            END;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_commandes_livreur') THEN
            BEGIN
                IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'app_users') THEN
                    ALTER TABLE commandes ADD CONSTRAINT fk_commandes_livreur FOREIGN KEY (livreur_id) REFERENCES app_users (id);
                ELSIF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'utilisateurs') THEN
                    ALTER TABLE commandes ADD CONSTRAINT fk_commandes_livreur FOREIGN KEY (livreur_id) REFERENCES utilisateurs (id);
                END IF;
            EXCEPTION WHEN OTHERS THEN
                NULL;
            END;
        END IF;
    END IF;

    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'commande_produits') THEN
        CREATE TABLE commande_produits (
            id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            commande_id    BIGINT NOT NULL,
            produit_id     BIGINT NOT NULL,
            quantite       INTEGER NOT NULL,
            prix_unitaire  NUMERIC(12, 2) NOT NULL
        );
    END IF;

    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'commande_produits') THEN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_commande_produits_commande') THEN
            BEGIN
                ALTER TABLE commande_produits ADD CONSTRAINT fk_commande_produits_commande FOREIGN KEY (commande_id) REFERENCES commandes (id);
            EXCEPTION WHEN OTHERS THEN
                NULL;
            END;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_commande_produits_produit') THEN
            BEGIN
                ALTER TABLE commande_produits ADD CONSTRAINT fk_commande_produits_produit FOREIGN KEY (produit_id) REFERENCES produits (id);
            EXCEPTION WHEN OTHERS THEN
                NULL;
            END;
        END IF;
    END IF;
END $$;
