CREATE TABLE partenaires (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom        VARCHAR(255) NOT NULL,
    telephone  VARCHAR(255) NOT NULL,
    CONSTRAINT uq_partenaires_nom UNIQUE (nom)
);
