DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'partenaires') THEN
        CREATE TABLE partenaires (
            id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nom        VARCHAR(255) NOT NULL,
            telephone  VARCHAR(255) NOT NULL
        );
    END IF;

    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'partenaires') THEN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_partenaires_nom') 
           AND NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'uq_partenaires_nom') THEN
            ALTER TABLE partenaires ADD CONSTRAINT uq_partenaires_nom UNIQUE (nom);
        END IF;
    END IF;
END $$;
