ALTER TABLE utilisateurs ADD COLUMN IF NOT EXISTS first_login BOOLEAN DEFAULT TRUE;
ALTER TABLE utilisateurs ADD COLUMN IF NOT EXISTS otp_code VARCHAR(10) NULL;
ALTER TABLE utilisateurs ADD COLUMN IF NOT EXISTS otp_expiry TIMESTAMP NULL;
ALTER TABLE utilisateurs ADD COLUMN IF NOT EXISTS otp_verified BOOLEAN DEFAULT FALSE;
