DO $$
BEGIN
    -- 1. Si la table 'app_users' existe et 'utilisateurs' n'existe pas, renommer 'app_users'
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'app_users') 
       AND NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'utilisateurs') THEN
        ALTER TABLE app_users RENAME TO utilisateurs;
    END IF;

    -- 2. Si la table 'utilisateurs' n'existe toujours pas, la créer entièrement
    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'utilisateurs') THEN
        CREATE TABLE utilisateurs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nom_utilisateur VARCHAR(255) NOT NULL,
            email VARCHAR(255),
            mot_de_passe VARCHAR(255) NOT NULL,
            nom VARCHAR(255),
            prenom VARCHAR(255),
            role VARCHAR(255) NOT NULL,
            date_creation TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
            first_login BOOLEAN NOT NULL DEFAULT TRUE,
            otp_code VARCHAR(10),
            otp_expiry TIMESTAMP(6),
            otp_verified BOOLEAN NOT NULL DEFAULT FALSE,
            CONSTRAINT uq_utilisateurs_nom_utilisateur UNIQUE (nom_utilisateur)
        );
    ELSE
        -- 3. Si la table existe déjà, s'assurer des renommages et de la présence des colonnes requises
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_name = 'utilisateurs' AND column_name = 'username') THEN
            ALTER TABLE utilisateurs RENAME COLUMN username TO nom_utilisateur;
        END IF;
        IF EXISTS (SELECT FROM information_schema.columns WHERE table_name = 'utilisateurs' AND column_name = 'password') THEN
            ALTER TABLE utilisateurs RENAME COLUMN password TO mot_de_passe;
        END IF;

        ALTER TABLE utilisateurs ADD COLUMN IF NOT EXISTS email VARCHAR(255);
        ALTER TABLE utilisateurs ADD COLUMN IF NOT EXISTS first_login BOOLEAN NOT NULL DEFAULT TRUE;
        ALTER TABLE utilisateurs ADD COLUMN IF NOT EXISTS otp_code VARCHAR(10);
        ALTER TABLE utilisateurs ADD COLUMN IF NOT EXISTS otp_expiry TIMESTAMP(6);
        ALTER TABLE utilisateurs ADD COLUMN IF NOT EXISTS otp_verified BOOLEAN NOT NULL DEFAULT FALSE;
    END IF;
END $$;
